### ISSUE TITLE
Software Security Architecture document development

### ISSUE THREAD

**Issue by RJSkudra** [LBTU-IT-M24/ClassMate#28]
### Description
While developing an SRS, we also need to create a separate document regarding security architecture

### TODO
- [x] Develop a security architecture document

**Comment by Vanshuk-Bhagat** [comment]
I will do this

**Comment by Kirishanth-Manivannan** [comment]
Document responsibility assigned to @Vanshuk-Bhagat 👍

**Comment by Vanshuk-Bhagat** [comment]
https://drive.google.com/drive/folders/1mf-UjeIsRFPBnK2YH1CQ1DwaKtY9NFiw?usp=sharing

**Comment by kitten-cake-png** [comment]
Hello, @Vanshuk-Bhagat!
Since you shared View only mode your Security Architecture document, Ill leave my feedback here.

The security architecture for ClassMate is well-structured and demonstrates a solid understanding of security principles. By adjusting the emphasis to align with the application's features - specifically, the absence of sensitive data and user authentication - the document can be made even more relevant and effective. Focusing on preventing disruptions, ensuring data integrity, and maintaining reliable service will help deliver a secure and trustworthy application.

- Adjust objectives and threat Priorities. 
Modify the objectives and threat model to reflect the actual risks pertinent to the application.

- Clarify applicability of security measures.
For each security control, explain how it applies to the project's context to ensure that resources are allocated efficiently.

- Emphasize relevant security practices. 
Focus on input validation, secure coding, and protection against common web vulnerabilities that could affect application availability and integrity.

- Review compliance needs. 
Verify any legal obligations related to data collected by the application, even if it's not sensitive.

**Comment by RJSkudra** [comment]
@Vanshuk-Bhagat Please copy over your documents to the shared project folder: https://drive.google.com/drive/folders/1yNcGAvcalONHNtkyUEGPPD_W9Xy69068?usp=drive_link

Also, can we close this issue or do we need a review or update @Kirishanth-Manivannan @Vanshuk-Bhagat ?
